export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";
export const DATA_FETCH_FAILED = "DATA_FETCH_FAILED";
export const DETAILS_FETCH_SUCCESS = "DETAILS_FETCH_SUCCESS";
export const DETAILS_FETCH_FAILED = "DETAILS_FETCH_FAILED";
