export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
export const PROFILE_FETCH_FAILED = "PROFILE_FETCH_FAILED";
export const ADMIN_PRODUCTS_FETCH_SUCCESS = "ADMIN_PRODUCTS_FETCH_SUCCESS";
export const ADMIN_PRODUCTS_FETCH_FAILED = "ADMIN_PRODUCTS_FETCH_FAILED";
export const ADMIN_PRODUCTS_DELETE_SUCCESS = "ADMIN_PRODUCTS_DELETE_SUCCESS";
export const ADMIN_PRODUCTS_DELETE_FAILED = "ADMIN_PRODUCTS_DELETE_FAILED";
